### ISSUE TITLE
How to modify #_flag

### ISSUE THREAD

**Issue by jasonesiegel** [trgkanki/flag_label#1]
Hi! I saw your add-on and was wondering if you have insight into the #_flag and #_mark elements. I have an advanced template and was attempting to style the flags and mark, but only with some success. Moreover, on mobile I can't seem to get them to hide, even with the style display: none !important. It's almost as if they have different code than <div id="#_flag">

Is this add-on done by modifying Anki's code, or is simply a style?

**Comment by phu54321** [comment]
simply a style.
