### ISSUE TITLE
Flag label not working

### ISSUE THREAD

**Issue by smitboss** [trgkanki/flag_label#2]
# Bug report

Not working with Anki Version ⁨2.1.49

## Describe the bug

Maybe because now the colour of flag has been changed I guess. Also now there are more than 4 flags.
Can you solve this issue please.

## Reproduction step

Nothing showing with flag on the review page.

## Expected behavior

It should give the added text with the flag.

## Actual behavior

Only showing the flag

## Anki/OS versions

- OS: Windows 11
- Anki version 2.1.49

## Additional context

I have tried changing the new colur in your addon but it didn't worked.

**Comment by smitboss** [comment]
Still no luck

**Comment by phu54321** [comment]
Should have been fixed with https://github.com/trgkanki/flag_label/commit/a431cdc13c3da9b2aa7b4c13723e811f391fcc25
